---
# Install postgresql packages

- name: unwanted packages are removed
  package:
    name: "{{ postgresql_packages_remove }}"
    state: absent
  become: true
  when: postgresql_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ postgresql_packages_repos }}"
    state: "{{ postgresql_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ postgresql_packages_prereq }}"
    state: "{{ postgresql_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ postgresql_packages_install }}"
    state: "{{ postgresql_packages_state }}"
  become: true
