---
# Template configuration files for postgresql

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ postgresql_templates_copy }}"
  when: postgresql_copy_templates
